apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: TrainingPortal
metadata:
  name: learning-center-guided
spec:
  portal:
    ingress:
      hostname: learning-center-guided
    registration:
      type: anonymous
    reserved: 0
    sessions:
      maximum: 10
    updates:
      workshop: true
  workshops:
  - name: lab-et-self-guided-tour
    expires: 30m
    orphaned: 10m
  - name: my-learning-center
    capacity: 1
    expires: 60m
    orphaned: 5m
