apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: my-learning-center
spec:
  title: My Learning Center
  description: My first Learning Center module.
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.com/jbergfeld/my-learning-center
  content:
    #image: jbergfeld/my-learning-center:master
    files: github.com/jbergfeld/my-learning-center
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
